import "./SignUpForm.scss";

// const countries = [
//   "Afganistán",
//   "Albania",
//   "Alemania",
//   "Andorra",
//   "Angola",
//   "Antigua y Barbuda",
//   "Arabia Saudita",
//   "Argelia",
//   "Argentina",
//   "Armenia",
//   "Australia",
//   "Austria",
//   "Azerbaiyán",
//   "Bahamas",
//   "Bangladés",
//   "Barbados",
//   "Baréin",
//   "Bélgica",
//   "Belice",
//   "Benín",
//   "Bielorrusia",
//   "Birmania/Myanmar",
//   "Bolivia",
//   "Bosnia y Herzegovina",
//   "Botsuana",
//   "Brasil",
//   "Brunéi",
//   "Bulgaria",
//   "Burkina Faso",
//   "Burundi",
//   "Bután",
//   "Cabo Verde",
//   "Camboya",
//   "Camerún",
//   "Canadá",
//   "Catar",
//   "Chad",
//   "Chile",
//   "China",
//   "Chipre",
//   "Ciudad del Vaticano",
//   "Colombia",
//   "Comoras",
//   "Corea del Norte",
//   "Corea del Sur",
//   "Costa de Marfil",
//   "Costa Rica",
//   "Croacia",
//   "Cuba",
//   "Dinamarca",
//   "Dominica",
//   "Ecuador",
//   "Egipto",
//   "El Salvador",
//   "Emiratos Árabes Unidos",
//   "Eritrea",
//   "Eslovaquia",
//   "Eslovenia",
//   "España",
//   "Estados Unidos",
//   "Estonia",
//   "Etiopía",
//   "Filipinas",
//   "Finlandia",
//   "Fiyi",
//   "Francia",
//   "Gabón",
//   "Gambia",
//   "Georgia",
//   "Ghana",
//   "Granada",
//   "Grecia",
//   "Guatemala",
//   "Guyana",
//   "Guinea",
//   "Guinea ecuatorial",
//   "Guinea-Bisáu",
//   "Haití",
//   "Honduras",
//   "Hungría",
//   "India",
//   "Indonesia",
//   "Irak",
//   "Irán",
//   "Irlanda",
//   "Islandia",
//   "Islas Marshall",
//   "Islas Salomón",
//   "Israel",
//   "Italia",
//   "Jamaica",
//   "Japón",
//   "Jordania",
//   "Kazajistán",
//   "Kenia",
//   "Kirguistán",
//   "Kiribati",
//   "Kuwait",
//   "Laos",
//   "Lesoto",
//   "Letonia",
//   "Líbano",
//   "Liberia",
//   "Libia",
//   "Liechtenstein",
//   "Lituania",
//   "Luxemburgo",
//   "Macedonia del Norte",
//   "Madagascar",
//   "Malasia",
//   "Malaui",
//   "Maldivas",
//   "Malí",
//   "Malta",
//   "Marruecos",
//   "Mauricio",
//   "Mauritania",
//   "México",
//   "Micronesia",
//   "Moldavia",
//   "Mónaco",
//   "Mongolia",
//   "Montenegro",
//   "Mozambique",
//   "Namibia",
//   "Nauru",
//   "Nepal",
//   "Nicaragua",
//   "Níger",
//   "Nigeria",
//   "Noruega",
//   "Nueva Zelanda",
//   "Omán",
//   "Países Bajos",
//   "Pakistán",
//   "Palaos",
//   "Panamá",
//   "Papúa Nueva Guinea",
//   "Paraguay",
//   "Perú",
//   "Polonia",
//   "Portugal",
//   "Reino Unido",
//   "República Centroafricana",
//   "República Checa",
//   "República del Congo",
//   "República Democrática del Congo",
//   "República Dominicana",
//   "República Sudafricana",
//   "Ruanda",
//   "Rumanía",
//   "Rusia",
//   "Samoa",
//   "San Cristóbal y Nieves",
//   "San Marino",
//   "San Vicente y las Granadinas",
//   "Santa Lucía",
//   "Santo Tomé y Príncipe",
//   "Senegal",
//   "Serbia",
//   "Seychelles",
//   "Sierra Leona",
//   "Singapur",
//   "Siria",
//   "Somalia",
//   "Sri Lanka",
//   "Suazilandia",
//   "Sudán",
//   "Sudán del Sur",
//   "Suecia",
//   "Suiza",
//   "Surinam",
//   "Tailandia",
//   "Tanzania",
//   "Tayikistán",
//   "Timor Oriental",
//   "Togo",
//   "Tonga",
//   "Trinidad y Tobago",
//   "Túnez",
//   "Turkmenistán",
//   "Turquía",
//   "Tuvalu",
//   "Ucrania",
//   "Uganda",
//   "Uruguay",
//   "Uzbekistán",
//   "Vanuatu",
//   "Venezuela",
//   "Vietnam",
//   "Yemen",
//   "Yibuti",
//   "Zambia",
//   "Zimbabue",
// ];

const SignUpForm = () => {
  return (
    <div className="sign-up-form">
      <h2 className="sign-up-form__title">Registráte</h2>
      <form className="sign-up-form__form">
        <label>
          <input type="text" placeholder="*Nombre" required />
        </label>
        <label>
          <input type="text" placeholder="*Apellido/s" required />
        </label>
        <label>
          <input type="text" placeholder="*Email" required />
        </label>
        <select id="lang" name="countries" required>
          <option value="afganistán">Afganistán</option>
          <option value="albania">Albania</option>
          <option value="alemania">Alemania</option>
          <option value="andorra">Andorra</option>
          <option value="angola">Angola</option>
          <option value="spain">Spain</option>
        </select>
        <input type="submit" value="Enviar" />
      </form>
    </div>
  );
};

export default SignUpForm;
